config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount Lookbook::Engine, at: "/lookbook"
  end

  resources :youtubes do
    resources :lessons, module: :youtubes
  end

  resources :communities
  resources :events
  resources :screencasts
  resources :newsletters
  resources :podcasts
  # get 'landing/index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get "/pages/*page", to: "pages#show"
  get "/guides/*page", to: "guides#show"

  resources :authors, path: 'people'

  resources :courses

  namespace :books do
    resources :free, only: [:index, :show]
  end
  resources :books

  resources :tags, path: 'learn'
  resources :users

  # root "pages#show", page: "index"
  root "books#index"

  resources :sitemap, only: %i[index], constraints: ->(req) { req.format == :xml }

   authenticate :user, ->(user) { user.admin? } do
     mount Avo::Engine, at: Avo.configuration.root_path
   end
end

app/views/shared/_all_courses_list.html.erb
<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 gap-16 md:gap-8 xl:gap-16 mb-20">
  <% @courses.each do |course| %>
    <div class="group flex flex-col justify-between">
        <%= link_to course_path(course) do %>
      <% unless course.cover.nil? || course.cover.empty? %>
        <div class="mb-8 w-full">
          <% unless course.cover.nil? || course.cover.empty? %>
            <div class="md:group-hover:-translate-y-4 duration-300 transition-all relative isolate overflow-hidden rounded-lg shadow-xl shadow-slate-800/10">
              <% if course.free %>
                <span class="text-base bg-green-500/80 absolute font-bold text-white px-2 inline-block py-1">Free </span>
              <% end %>
              <%= image_tag("courses/#{course.cover}", alt: "#{course.title}", class: "shrink-0 lg:mr-auto block") %>
            </div>
          <% end %>
        </div>
      <% end %>

      <div class="grow">
          <h3 class="font-custom mb-2 text-2xl font-bold leading-tight">
            <%= course.title %>
          </h3>
        <div class="mb-2"><%= course.content %></div>
        <div class="flex gap-1 text-base mb-4">
          <% course.tags.each do |item| %>
            <div class="">
              <%= link_to item, class: "text-red-500 bg-slate-100 px-2 py-1 hover:text-red-600" do %>
                <%= item.title %>
              <% end %>
            </div>
          <% end %>
        </div>

      </div>
        <% end %>
      <%= link_to "Go to the course", course.website_url, target: "_blank", class: "font-custom self-start border inline-block border-slate-800 px-4 py-2 bg-slate-800 hover:bg-slate-700 text-white" %>
    </div>
  <% end %>
</div>

app/views/shared/_all_tags.html.erb
<div class="flex flex-wrap gap-2">
  <%= @tags.map { |t| link_to(t.title, t, class: "text-red-500 hover:text-red-500 bg-slate-100 px-4 py-2 hover:bg-slate-200/50") }.join(" ").html_safe %>
</div>

app/views/shared/_author_card.html.erb
<section class="light-wrapper-bg">

  <% unless author.photo.nil? || author.photo.empty? %>
    <%= image_tag("authors/#{author.photo}", alt: "#{author.name}", class: "w-36 h-36 border-4 border-white -mt-28 mx-auto mb-4 shadow-md shadow-slate-900/10 border border-white rounded-full") %>
  <% end %>

  <h1 class="font-custom text-5xl mb-8 text-center font-bold"><%= author.name %></h1>

  <div class="flex flex-col lg:flex-row items-start gap-10 xl:gap-16">
    <div class="w-full lg:w-2/3">
      <div class="text-slate-600"><%= author.content %></div>
    </div>

    <div class="pt-2 font-custom text-slate-500 text-base flex flex-col w-full lg:w-1/3 gap-2 items-start justify-start">
      <% unless author.website_url.nil? || author.website_url.empty? %>
        <a href="#" class="flex gap-4 hover:text-violet-500 transition items-center">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4 mr-1"> <path stroke-linecap="round" stroke-linejoin="round" d="M13.19 8.688a4.5 4.5 0 011.242 7.244l-4.5 4.5a4.5 4.5 0 01-6.364-6.364l1.757-1.757m13.35-.622l1.757-1.757a4.5 4.5 0 00-6.364-6.364l-4.5 4.5a4.5 4.5 0 001.242 7.244" /> </svg>
          <%= author.website_url %> 
        </a>
      <% end %>

      <% unless author.twitter_url.nil? || author.twitter_url.empty? %>
        <a href="#" class="flex gap-4 hover:text-violet-500 transition items-center">
          <svg viewBox="0 0 24 24" aria-hidden="true" fill="currentColor" class="h-5 w-5"><path d="M20.055 7.983c.011.174.011.347.011.523 0 5.338-3.92 11.494-11.09 11.494v-.003A10.755 10.755 0 0 1 3 18.186c.308.038.618.057.928.058a7.655 7.655 0 0 0 4.841-1.733c-1.668-.032-3.13-1.16-3.642-2.805a3.753 3.753 0 0 0 1.76-.07C5.07 13.256 3.76 11.6 3.76 9.676v-.05a3.77 3.77 0 0 0 1.77.505C3.816 8.945 3.288 6.583 4.322 4.737c1.98 2.524 4.9 4.058 8.034 4.22a4.137 4.137 0 0 1 1.128-3.86A3.807 3.807 0 0 1 19 5.274a7.657 7.657 0 0 0 2.475-.98c-.29.934-.9 1.729-1.713 2.233A7.54 7.54 0 0 0 22 5.89a8.084 8.084 0 0 1-1.945 2.093Z"></path></svg>
          Follow on Twitter
        </a>
      <% end %>

      <% unless author.github_url.nil? || author.github_url.empty? %>
        <a href="#" class="flex gap-4 hover:text-violet-500 transition items-center">
          <svg viewBox="0 0 24 24" aria-hidden="true" fill="currentColor" class="h-5 w-5"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 2C6.475 2 2 6.588 2 12.253c0 4.537 2.862 8.369 6.838 9.727.5.09.687-.218.687-.487 0-.243-.013-1.05-.013-1.91C7 20.059 6.35 18.957 6.15 18.38c-.113-.295-.6-1.205-1.025-1.448-.35-.192-.85-.667-.013-.68.788-.012 1.35.744 1.538 1.051.9 1.551 2.338 1.116 2.912.846.088-.666.35-1.115.638-1.371-2.225-.256-4.55-1.14-4.55-5.062 0-1.115.387-2.038 1.025-2.756-.1-.256-.45-1.307.1-2.717 0 0 .837-.269 2.75 1.051.8-.23 1.65-.346 2.5-.346.85 0 1.7.115 2.5.346 1.912-1.333 2.75-1.05 2.75-1.05.55 1.409.2 2.46.1 2.716.637.718 1.025 1.628 1.025 2.756 0 3.934-2.337 4.806-4.562 5.062.362.32.675.936.675 1.897 0 1.371-.013 2.473-.013 2.82 0 .268.188.589.688.486a10.039 10.039 0 0 0 4.932-3.74A10.447 10.447 0 0 0 22 12.253C22 6.588 17.525 2 12 2Z"></path></svg>
          Follow on GitHub 
        </a>
      <% end %>

      <a href="#" class="flex hidden gap-4 hover:text-violet-500 transition items-center">
        <svg viewBox="0 0 24 24" aria-hidden="true" fill="currentColor" class="h-5 w-5"><path d="M12 3c-2.444 0-2.75.01-3.71.054-.959.044-1.613.196-2.185.418A4.412 4.412 0 0 0 4.51 4.511c-.5.5-.809 1.002-1.039 1.594-.222.572-.374 1.226-.418 2.184C3.01 9.25 3 9.556 3 12s.01 2.75.054 3.71c.044.959.196 1.613.418 2.185.23.592.538 1.094 1.039 1.595.5.5 1.002.808 1.594 1.038.572.222 1.226.374 2.184.418C9.25 20.99 9.556 21 12 21s2.75-.01 3.71-.054c.959-.044 1.613-.196 2.185-.419a4.412 4.412 0 0 0 1.595-1.038c.5-.5.808-1.002 1.038-1.594.222-.572.374-1.226.418-2.184.044-.96.054-1.267.054-3.711s-.01-2.75-.054-3.71c-.044-.959-.196-1.613-.419-2.185A4.412 4.412 0 0 0 19.49 4.51c-.5-.5-1.002-.809-1.594-1.039-.572-.222-1.226-.374-2.184-.418C14.75 3.01 14.444 3 12 3Zm0 1.622c2.403 0 2.688.009 3.637.052.877.04 1.354.187 1.67.31.421.163.72.358 1.036.673.315.315.51.615.673 1.035.123.317.27.794.31 1.671.043.95.052 1.234.052 3.637s-.009 2.688-.052 3.637c-.04.877-.187 1.354-.31 1.67-.163.421-.358.72-.673 1.036a2.79 2.79 0 0 1-1.035.673c-.317.123-.794.27-1.671.31-.95.043-1.234.052-3.637.052s-2.688-.009-3.637-.052c-.877-.04-1.354-.187-1.67-.31a2.789 2.789 0 0 1-1.036-.673 2.79 2.79 0 0 1-.673-1.035c-.123-.317-.27-.794-.31-1.671-.043-.95-.052-1.234-.052-3.637s.009-2.688.052-3.637c.04-.877.187-1.354.31-1.67.163-.421.358-.72.673-1.036.315-.315.615-.51 1.035-.673.317-.123.794-.27 1.671-.31.95-.043 1.234-.052 3.637-.052Z"></path><path d="M12 15a3 3 0 1 1 0-6 3 3 0 0 1 0 6Zm0-7.622a4.622 4.622 0 1 0 0 9.244 4.622 4.622 0 0 0 0-9.244Zm5.884-.182a1.08 1.08 0 1 1-2.16 0 1.08 1.08 0 0 1 2.16 0Z"></path></svg>
        Follow on Intagram 
      </a>
      <a href="#" class="flex gap-4 hidden hover:text-violet-500 transition items-center">
        <svg viewBox="0 0 24 24" fill="currentColor" class="h-5 w-5"><path d="M18.335 18.339H15.67v-4.177c0-.996-.02-2.278-1.39-2.278-1.389 0-1.601 1.084-1.601 2.205v4.25h-2.666V9.75h2.56v1.17h.035c.358-.674 1.228-1.387 2.528-1.387 2.7 0 3.2 1.778 3.2 4.091v4.715zM7.003 8.575a1.546 1.546 0 01-1.548-1.549 1.548 1.548 0 111.547 1.549zm1.336 9.764H5.666V9.75H8.34v8.589zM19.67 3H4.329C3.593 3 3 3.58 3 4.297v15.406C3 20.42 3.594 21 4.328 21h15.338C20.4 21 21 20.42 21 19.703V4.297C21 3.58 20.4 3 19.666 3h.003z"></path></svg>
        Follow on Linkedin 
      </a>
    </div>

  </div>
</section>

app/views/shared/_author_second.html.erb
<section class="flex flex-col border border-slate-200 p-5 sm:p-10 rounded-3xl items-start gap-10 xl:gap-12">

  <div class="w-full flex flex-col items-start gap-8">
    <% unless author.photo.nil? || author.photo.empty? %>
      <%= image_tag("authors/#{author.photo}", alt: "#{author.name}", class: "rounded-full h-64 aspect-[3/4] object-cover border-white") %>
    <% end %>
    <div>
      <%= link_to author do %>
      <h3 class="h2 mb-4 text-red-500 hover:text-red-600"><%= author.name %></h3>
    <% end %>
      <div class="text-slate-600"><%= author.content %></div>
    </div>
  </div>

    <div class="font-custom text-slate-500 text-base flex flex-col gap-2 items-start justify-start">
      <% unless author.website_url.nil? || author.website_url.empty? %>
        <a href="#" class="flex gap-4 hover:text-red-500 transition items-center">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4 mr-1"> <path stroke-linecap="round" stroke-linejoin="round" d="M13.19 8.688a4.5 4.5 0 011.242 7.244l-4.5 4.5a4.5 4.5 0 01-6.364-6.364l1.757-1.757m13.35-.622l1.757-1.757a4.5 4.5 0 00-6.364-6.364l-4.5 4.5a4.5 4.5 0 001.242 7.244" /> </svg>
          <%= author.website_url %> 
        </a>
      <% end %>

      <% unless author.twitter_url.nil? || author.twitter_url.empty? %>
        <a href="#" class="flex gap-4 hover:text-red-500 transition items-center">
          <svg viewBox="0 0 24 24" aria-hidden="true" fill="currentColor" class="h-5 w-5"><path d="M20.055 7.983c.011.174.011.347.011.523 0 5.338-3.92 11.494-11.09 11.494v-.003A10.755 10.755 0 0 1 3 18.186c.308.038.618.057.928.058a7.655 7.655 0 0 0 4.841-1.733c-1.668-.032-3.13-1.16-3.642-2.805a3.753 3.753 0 0 0 1.76-.07C5.07 13.256 3.76 11.6 3.76 9.676v-.05a3.77 3.77 0 0 0 1.77.505C3.816 8.945 3.288 6.583 4.322 4.737c1.98 2.524 4.9 4.058 8.034 4.22a4.137 4.137 0 0 1 1.128-3.86A3.807 3.807 0 0 1 19 5.274a7.657 7.657 0 0 0 2.475-.98c-.29.934-.9 1.729-1.713 2.233A7.54 7.54 0 0 0 22 5.89a8.084 8.084 0 0 1-1.945 2.093Z"></path></svg>
          Follow on Twitter
        </a>
      <% end %>

      <% unless author.github_url.nil? || author.github_url.empty? %>
        <a href="#" class="flex gap-4 hover:text-red-500 transition items-center">
          <svg viewBox="0 0 24 24" aria-hidden="true" fill="currentColor" class="h-5 w-5"><path fill-rule="evenodd" clip-rule="evenodd" d="M12 2C6.475 2 2 6.588 2 12.253c0 4.537 2.862 8.369 6.838 9.727.5.09.687-.218.687-.487 0-.243-.013-1.05-.013-1.91C7 20.059 6.35 18.957 6.15 18.38c-.113-.295-.6-1.205-1.025-1.448-.35-.192-.85-.667-.013-.68.788-.012 1.35.744 1.538 1.051.9 1.551 2.338 1.116 2.912.846.088-.666.35-1.115.638-1.371-2.225-.256-4.55-1.14-4.55-5.062 0-1.115.387-2.038 1.025-2.756-.1-.256-.45-1.307.1-2.717 0 0 .837-.269 2.75 1.051.8-.23 1.65-.346 2.5-.346.85 0 1.7.115 2.5.346 1.912-1.333 2.75-1.05 2.75-1.05.55 1.409.2 2.46.1 2.716.637.718 1.025 1.628 1.025 2.756 0 3.934-2.337 4.806-4.562 5.062.362.32.675.936.675 1.897 0 1.371-.013 2.473-.013 2.82 0 .268.188.589.688.486a10.039 10.039 0 0 0 4.932-3.74A10.447 10.447 0 0 0 22 12.253C22 6.588 17.525 2 12 2Z"></path></svg>
          Follow on GitHub 
        </a>
      <% end %>

      <a href="#" class="flex hidden gap-4 hover:text-red-500 transition items-center">
        <svg viewBox="0 0 24 24" aria-hidden="true" fill="currentColor" class="h-5 w-5"><path d="M12 3c-2.444 0-2.75.01-3.71.054-.959.044-1.613.196-2.185.418A4.412 4.412 0 0 0 4.51 4.511c-.5.5-.809 1.002-1.039 1.594-.222.572-.374 1.226-.418 2.184C3.01 9.25 3 9.556 3 12s.01 2.75.054 3.71c.044.959.196 1.613.418 2.185.23.592.538 1.094 1.039 1.595.5.5 1.002.808 1.594 1.038.572.222 1.226.374 2.184.418C9.25 20.99 9.556 21 12 21s2.75-.01 3.71-.054c.959-.044 1.613-.196 2.185-.419a4.412 4.412 0 0 0 1.595-1.038c.5-.5.808-1.002 1.038-1.594.222-.572.374-1.226.418-2.184.044-.96.054-1.267.054-3.711s-.01-2.75-.054-3.71c-.044-.959-.196-1.613-.419-2.185A4.412 4.412 0 0 0 19.49 4.51c-.5-.5-1.002-.809-1.594-1.039-.572-.222-1.226-.374-2.184-.418C14.75 3.01 14.444 3 12 3Zm0 1.622c2.403 0 2.688.009 3.637.052.877.04 1.354.187 1.67.31.421.163.72.358 1.036.673.315.315.51.615.673 1.035.123.317.27.794.31 1.671.043.95.052 1.234.052 3.637s-.009 2.688-.052 3.637c-.04.877-.187 1.354-.31 1.67-.163.421-.358.72-.673 1.036a2.79 2.79 0 0 1-1.035.673c-.317.123-.794.27-1.671.31-.95.043-1.234.052-3.637.052s-2.688-.009-3.637-.052c-.877-.04-1.354-.187-1.67-.31a2.789 2.789 0 0 1-1.036-.673 2.79 2.79 0 0 1-.673-1.035c-.123-.317-.27-.794-.31-1.671-.043-.95-.052-1.234-.052-3.637s.009-2.688.052-3.637c.04-.877.187-1.354.31-1.67.163-.421.358-.72.673-1.036.315-.315.615-.51 1.035-.673.317-.123.794-.27 1.671-.31.95-.043 1.234-.052 3.637-.052Z"></path><path d="M12 15a3 3 0 1 1 0-6 3 3 0 0 1 0 6Zm0-7.622a4.622 4.622 0 1 0 0 9.244 4.622 4.622 0 0 0 0-9.244Zm5.884-.182a1.08 1.08 0 1 1-2.16 0 1.08 1.08 0 0 1 2.16 0Z"></path></svg>
        Follow on Intagram 
      </a>
      <a href="#" class="flex gap-4 hidden hover:text-red-500 transition items-center">
        <svg viewBox="0 0 24 24" fill="currentColor" class="h-5 w-5"><path d="M18.335 18.339H15.67v-4.177c0-.996-.02-2.278-1.39-2.278-1.389 0-1.601 1.084-1.601 2.205v4.25h-2.666V9.75h2.56v1.17h.035c.358-.674 1.228-1.387 2.528-1.387 2.7 0 3.2 1.778 3.2 4.091v4.715zM7.003 8.575a1.546 1.546 0 01-1.548-1.549 1.548 1.548 0 111.547 1.549zm1.336 9.764H5.666V9.75H8.34v8.589zM19.67 3H4.329C3.593 3 3 3.58 3 4.297v15.406C3 20.42 3.594 21 4.328 21h15.338C20.4 21 21 20.42 21 19.703V4.297C21 3.58 20.4 3 19.666 3h.003z"></path></svg>
        Follow on Linkedin 
      </a>
    </div>

</section>

app/views/shared/_book_card.html.erb
<div class="flex flex-col md:flex-row gap-5 lg:gap-8">
  <% unless book.cover.nil? || book.cover.empty? %>
    <%= link_to book, class: "shrink-0 rounded-sm overflow-hidden hover:-translate-y-4 duration-300 transition-all self-start relative shadow-md hover:shadow-xl shadow-slate-800/20 " do %>
      <%= image_tag("books/overlay.png", alt: "", class: "absolute mix-blend-multiply inset-0") %>
      <%= image_tag("books/#{book.cover}", alt: "#{book.title}", class: "block w-44 sm:w-40 md:w-44 lg:w-64") %>
    <% end %>
    <% else %>
      <div>
        <%= link_to book, class:"bg-red-600 inline-block text-left shadow-md shadow-slate-800/20 rounded-md relative overflow-hidden mb-10 pt-4 lg:pt-10 p-4 text-white self-start aspect-[3/4] shrink-0 w-44 lg:w-64 mx-auto" do %>
          <%= image_tag("books/overlay.png", alt: "", class: "absolute mix-blend-multiply inset-0") %>
          <p class="text-base lg:pl-4"><%= book.authors.map { |author| author.name }.join(", ").html_safe %> </p>
          <p class="font-bold mt-10 leading-tight text-lg lg:text-2xl lg:pl-4 font-custom">
          <%= book.title %> </p>
        <% end %> 
      </div>
  <% end %>

  <div>
    <%= link_to book do %>
      <h3 class="hover:text-red-500 flex gap-2 items-center mb-2 text-xl font-bold lg:text-3xl font-custom leading-tight">
        <%= book.title %>
        <% if book.free %>
          <span class="text-sm bg-green-500 rounded-full font-bold text-white px-4 py-2">Free </span>
        <% end %>
      </h3>
    <% end %>

    <span class="font-normal mb-2 inline-block text-lg text-slate-700">
      by <%= book.authors.map { |author| link_to(author.name, author, class: "hover:text-red-500") }.join(", ").html_safe %>
    </span>

    <%= render "shared/tag_in_card", tags: book %>

    <div class="mb-4 text-slate-600 text-base"><%= truncate(book.content.to_plain_text, length: 232, omisson: '...', separator: ' ') %></div>

    <%= link_to "Details", book, class: "rounded-md shadow-lg shadow-slate-600/10 px-6 hover:bg-slate-700 py-2 inline-block bg-slate-800 text-white text-base lg:text-xl font-custom" %>
  </div>

</div>

app/views/shared/_btn_cta.html.erb
<% if btn.present? %>
  <%= link_to btn, target: "_blank", data: {:"splitbee-event" => "#{event}"}, class: "inline-block bg-amber-100 text-slate-800 hover:-translate-y-2 hover:shadow-purple-900/60 hover:bg-amber-200 hover:shadow-xl transition duration-300 rounded-lg shadow-sm shadow-purple-900/30 px-12 py-5 text-2xl font-bold font-custom" do %>
    <%= title %>
  <% end %>
<% end %>

app/views/shared/_event_card.html.erb
<div class="flex flex-col justify-between bg-white rounded-xl p-10 gap-4 md:gap-2">
  <div class="">
    <p class="mb-2">
    <%= event.date %>
    </p>
    <%= link_to event do %>
      <h3 class="font-custom mb-4 hover:opacity-90 font-bold text-3xl xl:text-4xl xl:leading-tight">
        <%= event.title %>
      </h3>
    <% end %>
    <div class="mb-4"><%= event.description %></div>
  </div>

  <div>
      <%= link_to "Open Event", event.url, target:"_blank", data: {:"splitbee-event" => "go to event"}, class: "rounded-md shadow-lg shadow-slate-600/10 px-6 hover:bg-slate-700 py-2 inline-block bg-slate-800 text-white text-base lg:text-xl font-custom" %>
  </div>
</div>

app/views/shared/_free_label.html.erb
<% if source.free %>
  <div class="bg-green-600 rounded-full inline-block text-white px-4 py-1 text-sm font-bold mb-1 font-custom">Free</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="disable-scrollbars lg:h-screen flex top-0 sticky flex-col lg:w-60">

  <div class="rounded-xl px-2 mt-4 lg:mt-0 lg:p-5">

    <div class="flex flex-wrap lg:flex-col [&>*]:rounded-lg [&>*]:bg-white/5 lg:gap-1 [&>*]:px-2 [&>*]:py-2 flex-row sm:gap-x-1 sm:gap-y-1 font-custom text-lg">

      <%= link_to root_path, class: "hover:opacity-60 transition font-custom font-bold" do %>
        Ruby <span class="text-red-500 ">&</span> Rails
      <% end %>

      <%= link_to tags_path, class: "hover:opacity-60 transition" do %>
        Topics 
      <% end %>

      <%= link_to books_path, class: "hover:opacity-60 transition" do %>
        Books
      <% end %>

      <%= link_to courses_path, class: "hover:opacity-60 transition" do %>
        Courses
      <% end %>

        <%= link_to youtubes_path, class: "relative hover:opacity-60 transition flex gap-1" do %>
          Youtube Courses 
          <span class="inline-block text-xs px-2 absolute right-0 top-0 self-start text-white bg-red-600 rounded-full">New</span>
        <% end %>

      <%= link_to screencasts_path, class: "hover:opacity-60 transition" do %>
        Screencasts 
      <% end %>

      <%= link_to newsletters_path, class: "hover:opacity-60 transition" do %>
        Newsletters 
      <% end %>

      <%= link_to podcasts_path, class: "hover:opacity-60 transition" do %>
        Podcasts 
      <% end %>

      <%= link_to authors_path, class: "hover:opacity-60 transition" do %>
        People 
      <% end %>

      <%= link_to communities_path, class: "hover:opacity-60 transition" do %>
        Communities 
      <% end %>

      <%= link_to events_path, class: "hidden hover:opacity-60 transition" do %>
        Events 
      <% end %>

      <%= link_to "/pages/about", class: "hover:opacity-60 transition" do %>
        About 
      <% end %>

      <%= link_to "https://friendlyrb.com?rel=rubyandrails.info&utm_source=rubyandrails.info", target: "_blank", class: "hidden lg:block" do %>
        <%= image_tag("communities/friendlyrb.png", alt: "Friendly.rb - Your friendly European Ruby Conference.") %>
        <p class="mt-4 text-sm"><strong>Friendly.rb</strong> - Your friendly European Ruby Conference</p>
      <% end %>

      <% if current_user.try(:admin?) %>
        <%= render "shared/btns_add" %>
      <% end %>
    </div>

  </div>

  <div class="flex items-center md:gap-5">
    <% if user_signed_in? %>

      <div>
        <% if current_user.admin? %>
          <span>🔥</span>
        <% end %>
        <%= link_to current_user.name, user_path(current_user) %>
      </div>

      <%= button_to destroy_user_session_path, method: :delete do %>
        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"> <path stroke-linecap="round" stroke-linejoin="round" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" /> </svg>
      <% end %>
    <% end %>
  </div>
</nav>

app/views/shared/_podcast_card.html.erb
<div class="grid md:grid-cols-2 rounded-xl gap-5 lg:gap-8">
  <% unless podcast.cover.empty? %>
    <%= link_to podcast, class: "shrink-0 rounded-sm relative " do %>
      <%= image_tag("podcasts/#{podcast.cover}", alt: "#{podcast.title}", class: "shadow-lg shadow-slate-800/10 block") %>
    <% end %>
  <% end %>

  <div>
    <%= link_to podcast do %>
      <h3 class="hover:text-red-500 flex gap-2 items-center mb-2 text-xl font-bold md:text-3xl font-custom leading-tight">
        <%= podcast.title %>
      </h3>
      <% unless podcast.authors.count.zero? %>
        <div class="opacity-60 mb-4">
          by <%= podcast.authors.map { |author| link_to(author.name, author, class: "hover:opacity-80") }.join(", ").html_safe %>
        </div>
      <% end %>
    <% end %>

    <div class="mb-4 text-slate-600 text-base"><%= podcast.content %></div>

    <%= link_to "Listen Podcast", podcast.url, target:"_blank", data: {:"splitbee-event" => "go to podcast"}, class: "rounded-md shadow-lg shadow-slate-600/10 px-6 hover:bg-slate-700 py-2 inline-block bg-slate-800 text-white text-base lg:text-xl font-custom" %>
  </div>

</div>