config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount Lookbook::Engine, at: "/lookbook"
  end

  resources :youtubes do
    resources :lessons, module: :youtubes
  end

  resources :communities
  resources :events
  resources :screencasts
  resources :newsletters
  resources :podcasts
  # get 'landing/index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get "/pages/*page", to: "pages#show"
  get "/guides/*page", to: "guides#show"

  resources :authors, path: 'people'

  resources :courses

  namespace :books do
    resources :free, only: [:index, :show]
  end
  resources :books

  resources :tags, path: 'learn'
  resources :users

  # root "pages#show", page: "index"
  root "books#index"

  resources :sitemap, only: %i[index], constraints: ->(req) { req.format == :xml }

   authenticate :user, ->(user) { user.admin? } do
     mount Avo::Engine, at: Avo.configuration.root_path
   end
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id          :bigint           not null, primary key
#  title       :string
#  description :string
#  date        :string
#  url         :string
#  active      :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  slug        :string
#
class Event < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, :description, :url, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["id", "title"]
  end
end

app/controllers/avo/events_controller.rb
# This controller has been generated to enable Rails' resource routes.
# More information on https://docs.avohq.io/2.0/controllers.html
class Avo::EventsController < Avo::ResourcesController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  before_action :authenticate_admin!, only: %i[new edit create update destroy]
  before_action :set_event, only: %i[show edit update destroy]

  layout "admin", only: %i[new edit]

  def index
    set_meta_tags title: "Events, hackathons and meetups", description: "Events, hackathons and meetups are all excellent opportunities to network and learn new skills.", keywords: "Event, Ruby, Ruby on Rails, best events about programming, hackaton, conference, meetup"
 
    @events = Event.all.order created_at: :desc
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new event_params
    if @event.save
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  def show
    @event = Event.friendly.find(params[:id])

    set_meta_tags title: "event #{@event.title}", description: "#{@event.title}. #{@event.description}", keywords: "#{@event.title}, event, Ruby, Ruby on Rails"
  end

  def edit
  end

  def update
    if @event.update event_params
      redirect_to event_path(@event)
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to event_path
  end

  private
  
  def set_event 
    @event = Event.friendly.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :description, :date, :url, :active)
  end

  def authenticate_admin!
    redirect_to root_path unless current_user.try(:admin?)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: @event, class: "text-slate-800") do |f| %>

  <div class="flex flex-col gap-1 mb-r">
    <%= f.label :title, class: "text-base" %>
    <%= f.text_field :title %>
  </div>

  <div class="flex flex-col gap-1 mb-r">
    <%= f.label :description, class: "text-base" %>
    <%= f.text_field :description %>
  </div>

 <div class="flex flex-col gap-1 mb-r">
    <%= f.label :date, class: "text-base" %>
    <%= f.text_field :date %>
  </div>

  <div class="flex flex-col gap-1 mb-r">
    <%= f.label :url, class: "text-base" %>
    <%= f.text_field :url %>
  </div>

  <div class="flex items-center mb-5 gap-2 mb-4">
    <%= f.check_box :active %>
    <%= f.label "Active", class: "text-base"  %>
  </div>

  <div>
    <%= f.submit class: "bg-red-600 text-white px-5 py-3" %>
  </div>

<% end %>

app/views/events/edit.html.erb
<h1 class="font-bold font-custom text-5xl max-w-xl mb-2">Edit event</h1>

<div class="bg-white p-10 mb-20 rounded-2xl">
<%= render 'form' %>
</div>

app/views/events/new.html.erb
<h1 class="font-bold font-custom text-5xl max-w-xl mb-2">New newsletter</h1>

<div class="bg-white p-10 mb-20 rounded-2xl">
  <%= render 'form' %>
</div>

app/views/events/show.html.erb
<div class="mb-20 max-w-4xl mx-auto">
  <div class="bg-white rounded-2xl  sm:mr-5 lg:mr-0 p-5 sm:p-8 md:p-12 mb-20  border border-slate-200">

    <div class="flex flex-col justify-between rounded-xl gap-4 md:gap-2">
      <div class="">
        <%= link_to "All Events", events_path, class: "hover:text-red-600 text-red-500 inline-block mb-4" %>
        <p class="mb-4 font-bold"><%= @event.date %></p>
        <h3 class="font-custom mb-4 hover:opacity-90 font-bold text-3xl xl:text-4xl xl:leading-tight">
          <%= @event.title %>
        </h3>
        <div class="mb-4"><%= @event.description %></div>
      </div>

      <div>
        <%= link_to "Open Event",  @event.url, target:"_blank", data: {:"splitbee-event" => "go to event"}, class: "rounded-md shadow-lg shadow-slate-600/10 px-6 hover:bg-slate-700 py-2 inline-block bg-slate-800 text-white text-base lg:text-xl font-custom" %>
      </div>
    </div>

  </div>

  <%= render "shared/suggestions_books" %>
</div>


<%= render "shared/btns_add", item: @event, path: edit_event_path(@event) %>