config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount Lookbook::Engine, at: "/lookbook"
  end

  resources :youtubes do
    resources :lessons, module: :youtubes
  end

  resources :communities
  resources :events
  resources :screencasts
  resources :newsletters
  resources :podcasts
  # get 'landing/index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get "/pages/*page", to: "pages#show"
  get "/guides/*page", to: "guides#show"

  resources :authors, path: 'people'

  resources :courses

  namespace :books do
    resources :free, only: [:index, :show]
  end
  resources :books

  resources :tags, path: 'learn'
  resources :users

  # root "pages#show", page: "index"
  root "books#index"

  resources :sitemap, only: %i[index], constraints: ->(req) { req.format == :xml }

   authenticate :user, ->(user) { user.admin? } do
     mount Avo::Engine, at: Avo.configuration.root_path
   end
end

app/models/lesson.rb
# == Schema Information
#
# Table name: lessons
#
#  id         :bigint           not null, primary key
#  title      :string
#  url        :string
#  youtube_id :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  slug       :string
#
class Lesson < ApplicationRecord
  extend FriendlyId

  friendly_id :title, use: :slugged

  belongs_to :youtube
  has_rich_text :description

  validates :title, :url, :description, presence: true

  def next
    Lesson.where("id > ?", id).limit(1).first
  end

  def prev
    Lesson.where("id < ?", id).last
  end

  def self.ransackable_attributes(auth_object = nil)
    ["id", "title"]
  end
end

app/models/youtube.rb
# == Schema Information
#
# Table name: youtubes
#
#  id          :bigint           not null, primary key
#  title       :string
#  cover       :string
#  description :string
#  url         :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  slug        :string
#
class Youtube < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_many :authorings, as: :authorabble, dependent: :destroy
  has_many :authors, through: :authorings

  has_many :taggings, as: :taggable, dependent: :destroy
  has_many :tags, through: :taggings

  has_many :lessons, dependent: :destroy

  validates :title, :url, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["id", "title"]
  end
end

app/controllers/avo/lessons_controller.rb
# This controller has been generated to enable Rails' resource routes.
# More information on https://docs.avohq.io/2.0/controllers.html
class Avo::LessonsController < Avo::ResourcesController
end

app/controllers/avo/youtubes_controller.rb
# This controller has been generated to enable Rails' resource routes.
# More information on https://docs.avohq.io/2.0/controllers.html
class Avo::YoutubesController < Avo::ResourcesController
end

app/controllers/youtubes/lessons_controller.rb
class Youtubes::LessonsController < ApplicationController
  
  before_action :authenticate_admin!, only: %i[new edit create update destroy]
  before_action :set_youtube
  before_action :set_lesson, only: %i[show edit update destroy]
  
  def index
  @lessons =  @youtube.lessons.order(created_at: :asc)
  end

  def new
    @lesson = @youtube.lessons.build
  end

  def create
    @lesson = @youtube.lessons.build(lesson_params)
    if @lesson.save
      redirect_to [@youtube, @lesson]
    else
      render :new
    end
  end

  def show
    @all_lessons = @youtube.lessons.count

    @with_tags = "" 
    @with_authors = @youtube.authors.empty?
    @with_related = ""
    @with_lessons = ""
    render layout:"show_page"
  end

  def edit

  end

  def update
    if @lesson.update lesson_params
      redirect_to [@youtube, @lesson] 
    else
      render :edit
    end
  end

  def destroy
    @lesson.destroy
    redirect_to youtubes_path
  end

  private

  def set_youtube
    @youtube = Youtube.friendly.find(params[:youtube_id])
  end

  def set_lesson
    @lesson = @youtube.lessons.friendly.find(params[:id])
  end

  def lesson_params
    params.require(:lesson).permit(:title, :description, :url)
  end

  def authenticate_admin!
    redirect_to root_path unless current_user.try(:admin?)
  end

end

app/controllers/youtubes_controller.rb
class YoutubesController < ApplicationController

  before_action :authenticate_admin!, only: %i[new edit create update destroy]
  before_action :set_youtube, only: %i[show edit update destroy]
  
  def index
    set_meta_tags title: "#{Youtube.count} Youtube courses about Ruby & Ruby on Rails", description: "", keywords: 'Youtube courses, free course, Ruby, Ruby 3, Ruby on Rails 7, Ruby on Rails 6, Hotwire, Turbo Frame, Stimulus, Vue with Rails, React with Rails, Tailwind with Rails, learn ruby, learn ruby on rails'

    filtered_youtube_courses = Youtube.ransack(title_cont: search_term).result

    @youtubes = filtered_youtube_courses.order(created_at: :desc)
    render layout:"index_page"
  end

  def new
    @youtube = Youtube.new
  end

  def create
    @youtube = Youtube.new youtube_params
    if @youtube.save
      redirect_to youtube_path(@youtube)
    else
      render :new
    end
  end

  def show
    @youtube = Youtube.friendly.find(params[:id])
    @first_lesson = first_lesson(params[:id]) 

    @related = Youtube.where(id: Youtube.pluck(:id).sample).limit(3)

    render layout:"show_page"
  end


  def edit

  end

  def update
    if @youtube.update youtube_params
      redirect_to youtube_path(@youtube)
    else
      render :edit
    end
  end

  def destroy
    @youtube.destroy
    redirect_to youtubes_path
  end

  private

  def first_lesson(lesson_id = nil)
    Lesson.find_by(id: lesson_id) || Lesson.first
  end

  def set_youtube
    @youtube = Youtube.friendly.find(params[:id])
  end

  def youtube_params
    params.require(:youtube).permit(:title, :description, :cover, :url, tag_ids: [], author_ids: [])
  end

  def authenticate_admin!
    redirect_to root_path unless current_user.try(:admin?)
  end

  def search_term
    params[:search_term]&.strip&.downcase
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/youtubes_helper.rb
module YoutubesHelper
end

app/views/youtubes/lessons/_form.html.erb
<%= form_with(model: [@youtube, @lesson], class: "text-stone-800") do |f| %>

  <div class="flex flex-col gap-1 mb-4">
    <%= f.label :title, class: "text-base" %>
    <%= f.text_field :title %>
  </div>

  <div class="flex flex-col gap-1 mb-4">
    <%= f.label :description, class: "text-base" %>
    <%= f.rich_text_area :description %>
  </div>

  <div class="flex flex-col gap-1 mb-4">
    <%= f.label :url, class: "text-base" %>
    <%= f.text_field :url %>
  </div>

  <div>
    <%= f.submit class: "bg-red-600 text-white px-5 py-3" %>
  </div>

<% end %>

app/views/youtubes/lessons/edit.html.erb
<h1 class="font-bold font-custom text-5xl max-w-xl mb-2">Edit</h1>

<div class="bg-white p-10 mb-20 rounded-2xl">
  <%= render 'form' %>
</div>

app/views/youtubes/lessons/index.html.erb
<div class="mb-20 max-w-5xl mt-10 mx-auto">

  <section class="p-8 mb-8 bg-white rounded-3xl border-2 border-slate-200/60">

    <section class="flex flex-col md:flex-row gap-10">
      <%= link_to youtube_path(@youtube), class: "shrink-0 flex h-12 w-12 backdrop-blur-sm bg-white/70 transition rounded-full justify-center hover:bg-white border border-indigo-100 items-center relative" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-5 h-5 mr-1"> <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" /> </svg>
      <% end %>

      <div>
        <h1 class="text-4xl mb-1 lg:text-5xl font-bold font-custom"><%= @youtube.title %></h1>
        <p class="opacity-80 max-w-lg"><%= @youtube.description %></p>
      </div>
    </section>
  </section>

  <section class="p-8 mb-8 bg-white rounded-3xl border-2 border-slate-200/60">
    <h2 class="text-4xl mb-8 font-bold font-custom">Lessons</h2>

    <div>
      <ul class="space-y-6">
        <% @lessons.order(created_at: :asc).each do |lesson| %>
          <li>
            <%= link_to lesson.title, [@youtube, lesson], class: "hover:text-red-500" %>
          </li>
        <% end %>
      </ul>
    </div>
  </section>
</div>

app/views/youtubes/lessons/new.html.erb
<h1 class="font-bold font-custom text-5xl max-w-xl mb-2">New</h1>

<div class="bg-white p-10 mb-20 rounded-2xl">
  <%= render 'form' %>
</div>

app/views/youtubes/lessons/show.html.erb
<% content_for :hero do %>
  <%#= render "shared/btn_back", path: youtubes_path %>

  <div class="flex-1">
    <div class="bg-blue-700 shadow-xl mb-8 shadow-blue-800/40 rounded-xl">
      <iframe class="aspect-video rounded-xl w-full" src="https://www.youtube.com/embed/<%= @lesson.url %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>

    <div class="flex justify-between mb-12">
      <div class="flex gap-4">

        <%= render "shared/btn_back", path: [@youtube] %>

      </div>

      <div class="flex gap-2">
        <%= link_to [@youtube, @lesson.prev], class: "flex gap-2 items-center uppercase hover:bg-slate-800/60 transition px-4 py-3  text-base font-custom font-bold rounded-lg backdrop-blur-md bg-slate-800/30 hover:text-white/70" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 12h-15m0 0l6.75 6.75M4.5 12l6.75-6.75" />
          </svg>
          Previous
        <% end %>

        <%= link_to youtube_lessons_path, class: "flex gap-2 items-center uppercase hover:bg-slate-800/60 transition px-4 py-3  text-base font-custom font-bold rounded-lg backdrop-blur-md bg-slate-800/30 hover:text-white/70" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12H12m-8.25 5.25h16.5" />
          </svg>
          All Lessons
        <% end %>

        <%= link_to [@youtube, @lesson.next], class: "flex gap-2 items-center uppercase hover:bg-slate-800/60 transition px-4 py-3  text-base font-custom font-bold rounded-lg backdrop-blur-md bg-slate-800/30 hover:text-white/70" do %>
          Next
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 12h15m0 0l-6.75-6.75M19.5 12l-6.75 6.75" />
          </svg>
        <% end %>
      </div>
    </div>

    <div class="text-left space-y-2 mb-8">

      <p>
      <%#= link_to "#{@youtube.lessons[3]} of #{@all_lessons} Lessons", youtube_lessons_path %>

      </p>
      <h1 class="h2"><%= @lesson.title %></h1>
    </div>
  </div>

  <% end %>

  <% content_for :content do %>
    <%= @lesson.description %>
  <% end %>

  <% content_for :authors do %>
  <%= render partial: "shared/author_second",  collection: @youtube.authors, as: :author %>
  <% end %>