config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount Lookbook::Engine, at: "/lookbook"
  end

  resources :youtubes do
    resources :lessons, module: :youtubes
  end

  resources :communities
  resources :events
  resources :screencasts
  resources :newsletters
  resources :podcasts
  # get 'landing/index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get "/pages/*page", to: "pages#show"
  get "/guides/*page", to: "guides#show"

  resources :authors, path: 'people'

  resources :courses

  namespace :books do
    resources :free, only: [:index, :show]
  end
  resources :books

  resources :tags, path: 'learn'
  resources :users

  # root "pages#show", page: "index"
  root "books#index"

  resources :sitemap, only: %i[index], constraints: ->(req) { req.format == :xml }

   authenticate :user, ->(user) { user.admin? } do
     mount Avo::Engine, at: Avo.configuration.root_path
   end
end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id                 :bigint           not null, primary key
#  title              :string
#  content            :text
#  free               :boolean
#  page               :integer
#  isbn               :string
#  amazon_url         :string
#  website_title      :string
#  website_url        :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  subtitle           :string
#  year               :integer
#  slug               :string
#  cover              :string
#  featured           :boolean
#
class Book < ApplicationRecord
  extend FriendlyId

  friendly_id :title, use: :slugged

  has_rich_text :content

  has_many :taggings, as: :taggable, dependent: :destroy
  has_many :tags, through: :taggings

  has_many :authorings, as: :authorabble, dependent: :destroy
  has_many :authors, through: :authorings

  validates :title, :content, presence: true

  def self.free_books
    where("free = ?", true)
  end

  def free?
    free.trust
  end

  def next
    self.class.where("id > ?", id).order("id ASC").first || Book.first
  end

  def previous
    self.class.where("id < ?", id).order("id DESC").first || Book.last
  end

  def self.ransackable_attributes(auth_object = nil)
    ["id", "title"]
  end
end

app/controllers/avo/books_controller.rb
# This controller has been generated to enable Rails' resource routes.
# More information on https://docs.avohq.io/2.0/controllers.html
class Avo::BooksController < Avo::ResourcesController
end

app/controllers/books/free_controller.rb
class Books::FreeController < ApplicationController
  def index
    set_meta_tags title: "#{Book.free_books.count} free books about Ruby & Ruby on Rails", description: "Find books that will help you learn new versions of Ruby 3, Ruby on Rails 7, Hotwire, TurboFrame, and become a better programmer in general", keywords: 'Book, free, Ruby, Ruby 3, Ruby on Rails 7, Ruby on Rails 6, Hotwire, Turbo Frame, Stimulus, Vue with Rails, React with Rails, Tailwind with Rails, learn ruby, learn ruby on rails'

    @books = Book.free_books
    @featured = Book.where(featured: true).where(free: true)
    @random = Book.where(id: Book.free_books.pluck(:id).sample) 
    @tags = Tag.all.order(:title)

    render layout:"index_page"
  end

  def show
    @book = Book.free_books.friendly.find(params[:id])

    @random_book = Book.where(id: Book.free_books.pluck(:id).sample) 
    @similar = Book.free_books.where(id: Book.free_books.pluck(:id).sample(3)) 
    @with_lessons = ""

    set_meta_tags title: "Free book #{@book.title}", description: "Free book #{@book.title} by #{@book.authors.map { |author| author.name}.join(", ").html_safe}. #{@book.content}", keywords: "#{@book.tags.map {|tag| tag.title}.join(", ").html_safe}, #{@book.title}, free, #{@book.authors.map { |author| author.name}.join(", ").html_safe}"

  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_admin!, only: %i[new edit create update destroy]
  before_action :set_book, only: %i[show edit update destroy]

  layout "admin", only: %i[new edit]

  def index
    set_meta_tags title: "#{Book.count} books about Ruby & Ruby on Rails", description: "The largest collection of books about Ruby & Ruby on Rails. Find books that will help you learn new versions of Ruby 3, Ruby on Rails 7, Hotwire, TurboFrame, and become a better programmer in general", keywords: 'Book, Ruby, Ruby 3, Ruby on Rails 7, Ruby on Rails 6, Hotwire, Turbo Frame, Stimulus, Vue with Rails, React with Rails, Tailwind with Rails, learn ruby, learn ruby on rails'
    @tags = Tag.all.order(:title)
    @pagy, @books = pagy(filter.filter(search_term))
    @featured = Book.where(featured: true).where(free: false)
    @random = Book.where(id: Book.pluck(:id).sample)

    render layout: "index_page"
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new book_params
    if @book.save
      redirect_to book_path(@book)
    else
      render :new
    end
  end

  def show
    @book = Book.friendly.find(params[:id])
    @random = Book.where(id: Book.pluck(:id).sample)

    tag_ids = @book.tags.pluck(:id)
    all_tags = Book.joins(:tags).where.not(books: {id: @book.id}).where(tags: { id: tag_ids}).limit(5)
    @similar = all_tags.uniq

    @with_tags = @book.tags.empty?
    @with_authors = @book.authors.empty?
    @with_related = @similar.empty?
    @with_lessons = ""

    set_meta_tags title: "Book #{@book.title}", description: "#{@book.title} by #{@book.authors.map { |author| author.name}.join(", ").html_safe}. #{@book.content}", keywords: "#{@book.tags.map {|tag| tag.title}.join(", ").html_safe}, #{@book.title}, #{@book.authors.map { |author| author.name}.join(", ").html_safe}"

    render layout:"show_page"
  end

  def edit

  end

  def update
    if @book.update book_params
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def set_book
    @book = Book.friendly.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :subtitle, :cover, :content, :free, :year, :page, :amazon_url, :website_title, :website_url, :featured, :isbn, tag_ids: [], author_ids: [])
  end

  def authenticate_admin!
    redirect_to root_path unless current_user.try(:admin?)
  end

  def search_term
    params[:search_term]&.strip&.downcase
  end

  def filter = Filter.new(Book)
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/free/_index_nav.html.erb
<div class="flex flex-wrap justify-between mb-8 xl:mb-16 gap-x-8 gap-y-2 md:gap-8">
  <div>
    <span class="h2">
      <%= link_to_unless_current "All Books", books_path, class: "text-red-500 hover:text-red-600" %>
    </span>
    <span class="h2">
      <%= link_to_unless_current "Free Books", books_free_index_path, class: "text-red-500 hover:text-red-600" %>
    </span>
  </div>

  <span class="h2">
    <% @random.each do |item| %>
      <%= link_to "🍀 Random Book", item, class: "text-red-500 hover:text-red-600" %>
    <% end %>
  </span>
</div>

app/views/books/free/index.html.erb
<% content_for :hero do %>
  <%= render "shared/page_title", title: "Free books about Ruby and Ruby on Rails", description: "If you're just getting started with Ruby or Ruby on Rails, I've collected some great free books that can help you out. There are plenty of free books available on these topics, so you can learn at your own pace and get up to speed quickly. Happy learning!", count: "#{Book.free_books.count} free books" %>
<% end %>

<% content_for :content do %>
  <%= render "books/index_nav" %>
  <%= render partial: "books/books_list", locals: { list: @books} %>
<% end %>

  <%#= render "shared/btns_add" %>

<div class="hidden">
  <%= render "shared/suggestions_books" %>
</div>

app/views/books/free/show.html.erb
<% content_for :hero do %>
  <%= render "shared/btn_back", path: books_path %>

  <div class="flex-1 flex flex-col gap-10 items-center">
    <%= render "shared/free_label", source: @book %>
    <div>
      <%= render partial: "books/book_cover", locals: { book: @book } %>

      <h1 class="h1 max-w-4xl mx-auto my-6">
        <%= @book.title %>
      </h1>
      <%= render "shared/btn_cta", btn: @book.website_url, event: "get book on publisher site", title: "#{@book.website_title}" %>

      <%= render "shared/btn_cta", btn: @book.amazon_url, event: "get book on amazon", title: "Amazon" %>
    </div>
  </div>
<% end %>

<% content_for :content do %>
  <%= @book.content %>

  <% if @book.website_url.present? %>
    <%= link_to @book.website_url, target: "_blank", data: {:"splitbee-event" => "Get Course"}, class: "bg-slate-900 text-center inline-block mt-8 text-white hover:bg-slate-700 transition duration-300 rounded-xl px-6 py-3 text-2xl font-bold font-custom" do %>
      Get Course
    <% end %>
  <% end %>
<% end %>

<% content_for :tags do %>
  <%= render "shared/tags_big", tag: @book.tags, btn: @book.website_url, event: "get book on publisher site" %>
<% end %>

<% content_for :authors do %>
  <%= render partial: "shared/author_second",  collection: @book.authors, as: :author %>
<% end %>

<% content_for :related do %>
  <div class="p-5 md:p-10 xl:p-16 grid sm:grid-cols-2 gap-8 text-slate-700 bg-white rounded-3xl ">
  <%= render partial: "books/card_compact", collection: @similar, as: :book %>
  </div>
<% end %>